modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://www.curseforge.com/minecraft/mc-mods/loot-all"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Sxilverr"
description = "Looting made easy."

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"
